export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const FETCH_REPO_START = 'FETCH_REPO_START';
export const FETCH_REPO_SUCCESS = 'FETCH_REPO_SUCCESS';
export const FETCH_REPO_FAILURE = 'FETCH_REPO_FAILURE';